### ISSUE TITLE
Add School Model and Methods to get School

### ISSUE THREAD

**Issue by leechongyan** [leechongyan/Studtor_backend#22]
Currently many methods are dependent on having school code, which has to be retrieved somewhere. 

Define school as well, I believe is SCSE, NBS etc

Create a model storing school information 
Create a method to retrieve a list of school 
Create a method to retrieve the information of a school

**Comment by Jordan396** [comment]
👍

**Comment by Jordan396** [comment]
Following our discussion, we will change the database tables to the following:

![image](https://user-images.githubusercontent.com/26784893/119630584-a9737580-be41-11eb-8189-900073dc5289.png)
(updated for issue #23 and #22)

For this change specifically:
- Addition of schools table. Every course must now belong to a school.

**Comment by Jordan396** [comment]
Resolved.
