### ISSUE TITLE
Link Tutor Id and User Id at creation

### ISSUE THREAD

**Issue by leechongyan** [leechongyan/Studtor_backend#23]
When creating user, should instantiate the user as a tutor also, else there is no way to know that the user id is attached to the tutor id. We need this as we are logged in as user, so we will get all the information at the start, and tutor id is definitely an important information for us to retrieve our booking time with students, etc.

**Comment by Jordan396** [comment]
Following our discussion, we will change the database tables to the following:

![image](https://user-images.githubusercontent.com/26784893/119630620-b42e0a80-be41-11eb-8aad-5fd46aceac56.png)
(updated for issue #23 and #22)

For this change specifically:
- Tutor table will be removed. Instead, we shall assume that all users are tutors.

**Comment by Jordan396** [comment]
Resolved.
