### ISSUE TITLE
schoolCoursesID issue

### ISSUE THREAD

**Issue by leechongyan** [leechongyan/Studtor_backend#27]
GetCoursesForSchoolByID(schoolCoursesID string) (schoolCourses []db_model.SchoolCoursesDetails, err error)

Get courses for school by id, should use school ID of type int as schoolcoursesid is a many to many relation table id and also it cannot be retrieved by a user to query this method.

**Comment by leechongyan** [comment]
Suggestion:
replacing that method with GetCoursesForSchool(school_id int) (courses db_model.CoursesForSchool, err error).

The school id is used to obtain the list of course id via the manytomany table, and then return the coursesforschool object to me

**Comment by Jordan396** [comment]
Resolved.
