### ISSUE TITLE
/auth endpoint

### ISSUE THREAD

**Issue by seaerchin** [leechongyan/Studtor_backend#3]
## Problem
It would be good for users to be able to sign in and this would allow for users to have unique properties that we could do greater work on. also because this is core to our functionality HAHA

## Proposed Solution
Create an endpoint rooted at `/auth` or `/login` with either `GET` or `POST`. Assignee should ideally post the return shape here because this blocks frontend

**Comment by leechongyan** [comment]
Please review pull request
